name: CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-service:
    name: Build Demo Service
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and test application
        run: |
          cd demo-service
          chmod +x gradlew
          ./gradlew build
  package-service:
    name: Package Demo Service
    needs: [build-service]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Containerize and publish image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage --publishImage --imageName nareshkalakanti/demo-service-goto:1.0 -PregistryUrl=${{ secrets.REGISTRY_URL }} -PregistryUsername=${{ secrets.REGISTRY_USERNAME }} -PregistryToken=${{ secrets.REGISTRY_TOKEN }}